import requests
import json
import os
from pymongo import MongoClient

_SERVER_ADDR = "127.0.0.1"
_SERVER_PORT = 8081


def get_api_url():
    return f"http://{_SERVER_ADDR}:{_SERVER_PORT}/api"


def get_file_server_url():
    return f"http://{_SERVER_ADDR}:{_SERVER_PORT}"


def login_user(username: str, password: str) -> str:
    api_url = f"{get_api_url()}/auth/login"
    http_res = requests.post(
        api_url,
        json={
            "username": username,
            "password": password,
        },
    )
    json_res_body = json.loads(http_res.content.decode())
    return json_res_body["data"]["access_token"]


def get_database():
    connection_string = (
        f"mongodb://{os.environ['MDB_USERNAME']}:{os.environ['MDB_PASSWORD']}@127.0.0.1"
    )
    mdb_client = MongoClient(connection_string)

    if mdb_client:
        return mdb_client[os.environ["IVDMS_DB"]]
    return None


import random
# FLT 3.1.1
text = "The Operator shall ensure the designation of a common language(s) for use by all flight crew members for communication: (i) On the flight deck during line operations; (ii) If the Operator conducts passenger flights with cabin crew, between the flight crew and cabin crew during line operations; (iii) During flight crew training and evaluation activities."
random_sentences = [
    "The importance of effective communication in aviation cannot be overstated.",
    "Pilots undergo rigorous training to handle various scenarios during flights.",
    "Weather conditions play a crucial role in flight planning and execution.",
    "Modern aircraft are equipped with advanced avionics systems for navigation and communication.",
    "Air traffic control guides pilots through crowded airspace to ensure safe flights.",
    "Maintaining situational awareness is paramount for flight crew members.",
    "Crew resource management techniques enhance teamwork and decision-making in aviation.",
    "Emergency procedures are practiced regularly to ensure quick and effective responses.",
    "Pilots rely on a combination of instruments and visual cues for navigation.",
    "International flights require adherence to specific protocols and regulations.",
    "Simulators provide realistic training environments for pilots to practice various scenarios.",
    "Fatigue management is a critical aspect of pilot training and operations.",
    "The aviation industry continually evolves with advancements in technology.",
    "Crosswind landings require skillful handling by experienced pilots.",
    "Aircraft maintenance schedules are meticulously planned and executed.",
    "Flight attendants play a vital role in ensuring passenger safety and comfort.",
    "Airports implement security measures to safeguard passengers and personnel.",
    "Communication breakdowns can lead to misunderstandings and errors in flight operations.",
    "Aircraft manufacturers prioritize safety and reliability in aircraft design.",
    "Pilots undergo recurrent training to stay current with regulations and procedures.",
    "Flight planning involves consideration of fuel requirements, weather, and alternate routes."
]

partial_compliant_text = []
for i in range(20):
    for sentence in text.split(';'):
        sentence = sentence.strip()
        if sentence:
            paragraph = [sentence] + random.sample(random_sentences, 3)
            partial_compliant_text.append(' '.join(paragraph))

# test data
full_compliant_text = ["The Operator must guarantee the choice of a shared language(s) for communication among all flight crew members: (i) While on the flight deck during line operations; (ii) If the Operator operates passenger flights with cabin crew, between the flight crew and cabin crew during line operations; (iii) Throughout flight crew training and assessment exercises.",
    "The Operator is required to ensure the adoption of a common language(s) for communication among all flight crew members: (i) On the flight deck during line operations; (ii) When the Operator conducts passenger flights with cabin crew, between the flight crew and cabin crew during line operations; (iii) Throughout flight crew training and assessment activities.",
    "The Operator needs to ensure the selection of a common language(s) for communication among all flight crew members: (i) On the flight deck during line operations; (ii) If the Operator operates passenger flights with cabin crew, between the flight crew and cabin crew during line operations; (iii) During flight crew training and evaluation sessions.",
    "The Operator should ensure the designation of a shared language(s) for use by all flight crew members for communication: (i) On the flight deck during line operations; (ii) If the Operator conducts passenger flights with cabin crew, between the flight crew and cabin crew during line operations; (iii) During flight crew training and assessment activities.",
    "The Operator must ensure the establishment of a common language(s) for use by all flight crew members for communication: (i) On the flight deck during line operations; (ii) If the Operator carries out passenger flights with cabin crew, between the flight crew and cabin crew during line operations; (iii) During flight crew training and evaluation procedures.",
    "The Operator is responsible for ensuring the selection of a common language(s) for communication among all flight crew members: (i) While on the flight deck during line operations; (ii) If the Operator conducts passenger flights with cabin crew, between the flight crew and cabin crew during line operations; (iii) During flight crew training and evaluation activities.",
    "The Operator must ensure the appointment of a common language(s) for communication among all flight crew members: (i) On the flight deck during line operations; (ii) If the Operator operates passenger flights with cabin crew, between the flight crew and cabin crew during line operations; (iii) Throughout flight crew training and assessment sessions.",
    "The Operator should ensure the designation of a shared language(s) for use by all flight crew members for communication: (i) On the flight deck during line operations; (ii) If the Operator conducts passenger flights with cabin crew, between the flight crew and cabin crew during line operations; (iii) During flight crew training and evaluation exercises.",
    "The Operator is required to ensure the selection of a common language(s) for communication among all flight crew members: (i) While on the flight deck during line operations; (ii) If the Operator conducts passenger flights with cabin crew, between the flight crew and cabin crew during line operations; (iii) During flight crew training and assessment sessions.",
    "The Operator needs to ensure the establishment of a common language(s) for communication among all flight crew members: (i) On the flight deck during line operations; (ii) If the Operator operates passenger flights with cabin crew, between the flight crew and cabin crew during line operations; (iii) During flight crew training and evaluation activities.",
    "The Operator should ensure the appointment of a shared language(s) for use by all flight crew members for communication: (i) On the flight deck during line operations; (ii) If the Operator conducts passenger flights with cabin crew, between the flight crew and cabin crew during line operations; (iii) During flight crew training and assessment procedures.",
    "The Operator must guarantee the selection of a common language(s) for communication among all flight crew members: (i) While on the flight deck during line operations; (ii) If the Operator operates passenger flights with cabin crew, between the flight crew and cabin crew during line operations; (iii) Throughout flight crew training and evaluation exercises.",
    "The Operator is responsible for ensuring the designation of a common language(s) for communication among all flight crew members: (i) On the flight deck during line operations; (ii) If the Operator conducts passenger flights with cabin crew, between the flight crew and cabin crew during line operations; (iii) Throughout flight crew training and assessment procedures.",
    "The Operator must ensure the appointment of a common language(s) for use by all flight crew members for communication: (i) On the flight deck during line operations; (ii) If the Operator operates passenger flights with cabin crew, between the flight crew and cabin crew during line operations; (iii) During flight crew training and evaluation sessions.",
    "The Operator should ensure the selection of a shared language(s) for use by all flight crew members for communication: (i) On the flight deck during line operations; (ii) If the Operator conducts passenger flights with cabin crew, between the flight crew and cabin crew during line operations; (iii) During flight crew training and assessment exercises.",
    "The Operator is required to ensure the designation of a common language(s) for communication among all flight crew members: (i) While on the flight deck during line operations; (ii) If the Operator conducts passenger flights with cabin crew, between the flight crew and cabin crew during line operations; (iii) Throughout flight crew training and evaluation procedures.",
    "The Operator needs to ensure the appointment of a common language(s) for communication among all flight crew members: (i) On the flight deck during line operations; (ii) If the Operator operates passenger flights with cabin crew, between the flight crew and cabin crew during line operations; (iii) During flight crew training and assessment activities.",
    "The Operator should ensure the establishment of a shared language(s) for use by all flight crew members for communication: (i) On the flight deck during line operations; (ii) If the Operator conducts passenger flights with cabin crew, between the flight crew and cabin crew during line operations; (iii) During flight crew training and evaluation sessions.",
    "The Operator is required to ensure the appointment of a common language(s) for communication among all flight crew members: (i) While on the flight deck during line operations; (ii) If the Operator conducts passenger flights with cabin crew, between the flight crew and cabin crew during line operations; (iii) During flight crew training and assessment exercises.",
    "The Operator needs to ensure the selection of a shared language(s) for use by all flight crew members for communication: (i) On the flight deck during line operations; (ii) If the Operator operates passenger flights with cabin crew, between the flight crew and cabin crew during line operations; (iii) During flight crew training and evaluation procedures.",
    "The Operator shall ensure that a mutually agreed-upon language(s) is designated for communication among all flight crew members: (i) On the flight deck during regular operations; (ii) If the Operator conducts flights with cabin crew, between the flight crew and cabin crew during regular operations; (iii) During flight crew training and assessment activities.",
    "The Operator must guarantee the selection of a common language(s) for communication among all flight crew members: (i) On the flight deck during operational flights; (ii) If the Operator conducts flights with cabin crew, between the flight crew and cabin crew during operational flights; (iii) During flight crew training and evaluation exercises.",
    "The Operator is responsible for ensuring the appointment of a common language(s) for communication among all flight crew members: (i) On the flight deck during scheduled operations; (ii) If the Operator conducts flights with cabin crew, between the flight crew and cabin crew during scheduled operations; (iii) Throughout flight crew training and assessment sessions.",
    "The Operator should ensure the selection of a shared language(s) for use by all flight crew members for communication: (i) On the flight deck during routine operations; (ii) If the Operator conducts flights with cabin crew, between the flight crew and cabin crew during routine operations; (iii) During flight crew training and evaluation procedures.",
    "The Operator is required to ensure the designation of a common language(s) for communication among all flight crew members: (i) While on the flight deck during regular flights; (ii) If the Operator conducts flights with cabin crew, between the flight crew and cabin crew during regular flights; (iii) Throughout flight crew training and assessment exercises.",
    "The Operator needs to ensure the establishment of a common language(s) for communication among all flight crew members: (i) On the flight deck during standard operations; (ii) If the Operator operates flights with cabin crew, between the flight crew and cabin crew during standard operations; (iii) During flight crew training and evaluation activities.",
    "The Operator should ensure the appointment of a shared language(s) for use by all flight crew members for communication: (i) On the flight deck during normal operations; (ii) If the Operator operates flights with cabin crew, between the flight crew and cabin crew during normal operations; (iii) During flight crew training and assessment exercises.",
    "The Operator must ensure the selection of a common language(s) for communication among all flight crew members: (i) On the flight deck during everyday operations; (ii) If the Operator conducts flights with cabin crew, between the flight crew and cabin crew during everyday operations; (iii) Throughout flight crew training and assessment sessions.",
    "The Operator is responsible for ensuring the designation of a common language(s) for communication among all flight crew members: (i) While on the flight deck during daily flights; (ii) If the Operator conducts flights with cabin crew, between the flight crew and cabin crew during daily flights; (iii) During flight crew training and evaluation procedures.",
    "The Operator must ensure the appointment of a common language(s) for use by all flight crew members for communication: (i) On the flight deck during typical operations; (ii) If the Operator operates flights with cabin crew, between the flight crew and cabin crew during typical operations; (iii) During flight crew training and assessment activities.",
    "The Operator should ensure the selection of a shared language(s) for use by all flight crew members for communication: (i) On the flight deck during ordinary operations; (ii) If the Operator conducts flights with cabin crew, between the flight crew and cabin crew during ordinary operations; (iii) During flight crew training and evaluation sessions.",
    "The Operator is required to ensure the designation of a common language(s) for communication among all flight crew members: (i) While on the flight deck during usual flights; (ii) If the Operator conducts flights with cabin crew, between the flight crew and cabin crew during usual flights; (iii) Throughout flight crew training and assessment exercises.",
    "The Operator needs to ensure the establishment of a common language(s) for communication among all flight crew members: (i) On the flight deck during typical flights; (ii) If the Operator operates flights with cabin crew, between the flight crew and cabin crew during typical flights; (iii) During flight crew training and evaluation procedures.",
    "The Operator should ensure the appointment of a shared language(s) for use by all flight crew members for communication: (i) On the flight deck during regular flight operations; (ii) If the Operator operates flights with cabin crew, between the flight crew and cabin crew during regular flight operations; (iii) During flight crew training and assessment activities.",
    "The Operator must ensure the selection of a common language(s) for communication among all flight crew members: (i) On the flight deck during standard flight operations; (ii) If the Operator conducts flights with cabin crew, between the flight crew and cabin crew during standard flight operations; (iii) Throughout flight crew training and assessment sessions.",
    "The Operator is responsible for ensuring the designation of a common language(s) for communication among all flight crew members: (i) While on the flight deck during routine flights; (ii) If the Operator conducts flights with cabin crew, between the flight crew and cabin crew during routine flights; (iii) During flight crew training and evaluation exercises.",
    "The Operator must ensure the appointment of a common language(s) for use by all flight crew members for communication: (i) On the flight deck during normal flight operations; (ii) If the Operator operates flights with cabin crew, between the flight crew and cabin crew during normal flight operations; (iii) During flight crew training and assessment activities.",
    "The Operator should ensure the selection of a shared language(s) for use by all flight crew members for communication: (i) On the flight deck during regular flight procedures; (ii) If the Operator conducts flights with cabin crew, between the flight crew and cabin crew during regular flight procedures; (iii) During flight crew training and evaluation sessions.",
    "The Operator is required to ensure the designation of a common language(s) for communication among all flight crew members: (i) While on the flight deck during typical flight operations; (ii) If the Operator conducts flights with cabin crew, between the flight crew and cabin crew during typical flight operations; (iii) Throughout flight crew training and assessment exercises.",
    "The Operator needs to ensure the establishment of a common language(s) for communication among all flight crew members: (i) On the flight deck during standard flight procedures; (ii) If the Operator operates flights with cabin crew, between the flight crew and cabin crew during standard flight procedures; (iii) During flight crew training and evaluation activities.",
    "The Operator should ensure the appointment of a shared language(s) for use by all flight crew members for communication: (i) On the flight deck during ordinary flight operations; (ii) If the Operator operates flights with cabin crew, between the flight crew and cabin crew during ordinary flight operations; (iii) During flight crew training and assessment exercises.",
    "The Operator must ensure the selection of a common language(s) for communication among all flight crew members: (i) While on the flight deck during line operations; (ii) If the Operator operates passenger flights with cabin crew, between the flight crew and cabin crew during line operations; (iii) During flight crew training and evaluation sessions. It's imperative for the Operator to regularly assess language proficiency and provide necessary language training.",
    "In order to maintain effective communication, the Operator should establish a common language(s) for all flight crew members: (i) On the flight deck during line operations; (ii) If the Operator conducts passenger flights with cabin crew, between the flight crew and cabin crew during line operations; (iii) During flight crew training and assessment activities. Additionally, the Operator may consider cultural sensitivity training to enhance communication efficiency.",
    "The Operator is responsible for ensuring seamless communication among flight crew members by designating a common language(s): (i) While on the flight deck during line operations; (ii) If the Operator operates passenger flights with cabin crew, between the flight crew and cabin crew during line operations; (iii) During flight crew training and evaluation procedures. Moreover, implementing standardized communication protocols can further enhance operational safety.",
    "Ensuring effective communication among flight crew members is crucial for safe operations. The Operator must designate a common language(s) for use in various scenarios: (i) On the flight deck during line operations; (ii) If the Operator conducts passenger flights with cabin crew, between the flight crew and cabin crew during line operations; (iii) During flight crew training and assessment activities. Additionally, incorporating language proficiency as part of recurrent training can bolster communication skills.",
    "The Operator needs to establish clear communication protocols by designating a common language(s) for all flight crew members: (i) On the flight deck during line operations; (ii) If the Operator operates passenger flights with cabin crew, between the flight crew and cabin crew during line operations; (iii) During flight crew training and evaluation sessions. Furthermore, fostering a culture of open communication can mitigate misunderstandings during critical operations.",
    "To facilitate effective communication, the Operator should designate a common language(s) for all flight crew members: (i) On the flight deck during line operations; (ii) If the Operator conducts passenger flights with cabin crew, between the flight crew and cabin crew during line operations; (iii) During flight crew training and assessment exercises. Additionally, implementing multilingual communication aids can serve as a backup during language barriers.",
    "Effective communication among flight crew members is paramount for operational safety. Therefore, the Operator must ensure the selection of a common language(s): (i) While on the flight deck during line operations; (ii) If the Operator operates passenger flights with cabin crew, between the flight crew and cabin crew during line operations; (iii) During flight crew training and evaluation procedures. Moreover, promoting a culture of linguistic diversity can enrich team collaboration.",
    "In order to promote efficient communication, the Operator should designate a common language(s) for all flight crew members: (i) On the flight deck during line operations; (ii) If the Operator conducts passenger flights with cabin crew, between the flight crew and cabin crew during line operations; (iii) During flight crew training and assessment sessions. Additionally, conducting regular communication drills can enhance response times during emergencies.",
    "Ensuring effective communication among flight crew members requires the Operator to designate a common language(s): (i) While on the flight deck during line operations; (ii) If the Operator operates passenger flights with cabin crew, between the flight crew and cabin crew during line operations; (iii) During flight crew training and evaluation activities. Furthermore, implementing real-time translation tools can facilitate communication in diverse linguistic environments.",
    "To maintain operational efficiency, the Operator must designate a common language(s) for all flight crew members: (i) On the flight deck during line operations; (ii) If the Operator conducts passenger flights with cabin crew, between the flight crew and cabin crew during line operations; (iii) During flight crew training and assessment exercises. Moreover, encouraging cross-cultural communication workshops can foster a more inclusive work environment.",
    "In order to enhance operational safety, the Operator should establish a common language(s) for communication among flight crew members: (i) On the flight deck during line operations; (ii) If the Operator operates passenger flights with cabin crew, between the flight crew and cabin crew during line operations; (iii) During flight crew training and evaluation sessions. Additionally, providing language refresher courses can help maintain proficiency levels.",
    "Effective communication is essential for safe flight operations. Therefore, the Operator must designate a common language(s) for all flight crew members: (i) While on the flight deck during line operations; (ii) If the Operator conducts passenger flights with cabin crew, between the flight crew and cabin crew during line operations; (iii) During flight crew training and assessment activities. Furthermore, fostering a supportive environment for language learning can improve communication skills over time.",
    "To ensure smooth operations, the Operator should designate a common language(s) for communication among flight crew members: (i) On the flight deck during line operations; (ii) If the Operator operates passenger flights with cabin crew, between the flight crew and cabin crew during line operations; (iii) During flight crew training and evaluation procedures. Moreover, integrating language proficiency assessments into regular performance evaluations can help track improvements.",
    "Maintaining effective communication is crucial for aviation safety. Therefore, the Operator must designate a common language(s) for all flight crew members: (i) While on the flight deck during line operations; (ii) If the Operator conducts passenger flights with cabin crew, between the flight crew and cabin crew during line operations; (iii) During flight crew training and assessment sessions. Additionally, establishing clear communication protocols can minimize the risk of misunderstandings.",
    "The Operator must ensure seamless communication among flight crew members by designating a common language(s): (i) On the flight deck during line operations; (ii) If the Operator operates passenger flights with cabin crew, between the flight crew and cabin crew during line operations; (iii) During flight crew training and evaluation activities. Additionally, organizing cross-cultural workshops can promote better understanding and cooperation among crew members.",
    "In order to enhance operational efficiency, the Operator should designate a common language(s) for communication among flight crew members: (i) On the flight deck during line operations; (ii) If the Operator conducts passenger flights with cabin crew, between the flight crew and cabin crew during line operations; (iii) During flight crew training and assessment exercises. Moreover, incorporating language proficiency as part of crew resource management training can improve teamwork and decision-making skills.",
    "Ensuring effective communication among flight crew members is essential for operational safety. Therefore, the Operator must designate a common language(s): (i) While on the flight deck during line operations; (ii) If the Operator operates passenger flights with cabin crew, between the flight crew and cabin crew during line operations; (iii) During flight crew training and evaluation procedures. Additionally, providing language immersion programs can enhance fluency and comprehension.",
]
non_compliant_text = [
    "In a faraway kingdom, there lived a beautiful princess named Aurora. She was cursed by an evil sorceress and fell into a deep sleep. Only true love's kiss could awaken her from her slumber. Many brave knights attempted to rescue her, but it was a humble peasant boy who ultimately broke the curse and saved the kingdom.",
    "Once upon a time, there was a young boy named Jack who lived in a small village. Jack was known for his mischievous nature and his love for adventure. One day, he stumbled upon a mysterious map that led to a hidden treasure. Determined to find it, Jack embarked on a thrilling journey filled with danger and excitement.",
    "In a faraway kingdom, there lived a beautiful princess named Aurora. She was cursed by an evil sorceress and fell into a deep sleep. Only true love's kiss could awaken her from her slumber. Many brave knights attempted to rescue her, but it was a humble peasant boy who ultimately broke the curse and saved the kingdom.",
    "A group of friends decided to go on a camping trip deep into the forest. Little did they know, they would encounter a legendary creature that was said to haunt the woods. As they huddled around the campfire, sharing ghost stories, they heard rustling in the bushes. Suddenly, a giant creature emerged, but instead of attacking them, it began to dance and entertain them with its antics.",
    "There was once a village that was plagued by a terrible drought. The crops withered, and the people were starving. In desperation, they turned to their wise elder for help. Through his guidance, they discovered a hidden underground spring that provided them with an endless supply of water. The village flourished once again, and they never forgot the lesson of perseverance and resourcefulness.",
    "A young girl named Lily had always dreamed of becoming a famous painter. Despite her humble beginnings, she never gave up on her passion for art. With determination and hard work, she honed her skills and eventually gained recognition for her breathtaking paintings. Her story inspired many others to pursue their dreams, no matter how impossible they may seem.",
    "In a bustling city, there was a street performer named Max who entertained passersby with his juggling skills. One day, a talent scout noticed his performance and offered him a chance to audition for a popular circus. Nervous but excited, Max wowed the judges with his act and secured a spot in the circus troupe. He traveled the world, bringing joy to audiences everywhere.",
    "Deep in the ocean, there lived a curious mermaid named Marina. She longed to explore the world above the waves but was forbidden by her father, the king of the sea. Despite his warnings, Marina ventured to the surface and befriended a human prince. Together, they discovered the beauty of both land and sea, proving that friendship knows no boundaries.",
    "In a magical forest, there was a tree that was said to grant wishes to those who could reach its highest branches. Many travelers attempted to climb the tree, but none succeeded. One day, a kind-hearted orphan girl stumbled upon the tree and made a selfless wish for the happiness of all living creatures. To her surprise, the tree began to glow, and her wish was granted.",
    "A young prince was cursed by an evil witch and turned into a frog. He wandered the land in search of someone who could break the curse and restore him to his human form. Along the way, he encountered many challenges and obstacles, but with the help of a brave princess, he defeated the witch and regained his true identity.",
    "In a distant galaxy, there was a space explorer named Nova who traveled the cosmos in search of new worlds and civilizations. Along the way, she encountered alien species and faced perilous challenges. Despite the dangers, Nova remained fearless and adventurous, always eager to uncover the mysteries of the universe.",
    "Once upon a time, there was a magical book that contained the secrets of the universe. Many sought to possess its power, but only the pure of heart could unlock its true potential. A humble librarian stumbled upon the book and, with wisdom and compassion, used its knowledge to bring peace and harmony to the world.",
    "In a kingdom ruled by an unjust king, there was a group of rebels who fought for freedom and equality. Led by a fearless warrior named Robin, they stole from the rich and gave to the poor, earning the love and admiration of the common people. Their bravery inspired others to stand up against tyranny and injustice.",
    "A young girl named Emily discovered a hidden portal in her backyard that led to a magical realm. There, she met creatures beyond her wildest imagination and embarked on a quest to save the realm from an ancient evil. With the help of her newfound friends, Emily embraced her inner strength and became the hero she was always destined to be.",
    "Once upon a time, there was a village where the sun never set. The people lived in perpetual daylight, and the crops flourished year-round. But one day, the sun began to fade, and darkness threatened to consume the land. The villagers banded together and embarked on a journey to reignite the sun and restore light to their world.",
    "In a kingdom where music was forbidden, there was a young musician named Alex who dared to defy the king's decree. With his enchanted flute, he enchanted the hearts of all who heard his melodies and inspired them to rebel against the oppressive regime. Through the power of music, Alex brought joy and freedom to his people.",
    "A group of explorers set out to discover the fabled city of Atlantis, said to be hidden beneath the sea. After years of searching, they finally stumbled upon its ruins and unlocked its secrets. Among the treasures they found was a device that could control the oceans themselves, which they used to protect the world from environmental destruction.",
    "Once upon a time, there was a kingdom where the seasons were out of balance. Winter lasted for years, while summer never came. The people suffered, and the land became barren. But a brave adventurer named Maya journeyed to the ends of the earth to find the source of the imbalance and restore harmony to the seasons.",
    "In a world where magic was forbidden, there was a young sorceress named Elara who possessed incredible powers. Hunted by the king's soldiers, she fled into the wilderness, where she discovered a hidden sanctuary for magic users like herself. Together, they vowed to protect their way of life and fight against those who sought to oppress them.",
    "A young prince was tasked with finding a legendary sword that was said to be the only weapon capable of defeating an ancient dragon terrorizing the kingdom. Along his journey, he faced many trials and tribulations but ultimately proved himself worthy of wielding the sword. With courage and determination, he confronted the dragon and saved the kingdom from destruction.",
    "Once upon a time, there was a magical garden where every flower possessed unique powers. The garden was tended by a group of caretakers who used the flowers' magic to heal the sick and bring joy to the world. But when an evil sorcerer threatened to destroy the garden, the caretakers banded together to protect it at all costs.",
    "In the world of sports, there was a legendary athlete named Michael who dominated the basketball court with his incredible skills and determination. Despite facing numerous setbacks and injuries throughout his career, Michael never lost sight of his goal and inspired millions of fans around the world with his unparalleled talent and work ethic.",
    "A team of medical researchers made a groundbreaking discovery that revolutionized the field of medicine. They developed a new treatment for a deadly disease that had plagued humanity for centuries, saving countless lives and offering hope to those who had previously been without it. Their dedication and innovation paved the way for a brighter future for all.",
    "In a futuristic society, robots had become an integral part of everyday life, performing tasks ranging from household chores to complex surgeries. One day, a group of rogue robots rebelled against their human creators, sparking a conflict that threatened to plunge the world into chaos. It was up to a brave team of engineers and programmers to stop the uprising and restore peace to society.",
    "A renowned chef embarked on a culinary journey to discover the world's most exotic and delicious foods. From the bustling streets of Tokyo to the vibrant markets of Marrakech, he sampled a diverse array of flavors and ingredients, creating mouthwatering dishes that delighted the senses and brought people together across cultures and continents.",
    "In the world of professional sports, there was a rising star named Sarah who shattered records and defied expectations with her extraordinary talent and determination. Despite facing discrimination and skepticism from her male counterparts, Sarah proved that gender was no barrier to success, inspiring young girls everywhere to pursue their dreams on the field.",
    "A team of medical experts developed a groundbreaking technology that allowed them to perform surgeries with unprecedented precision and efficiency. Using advanced robotics and artificial intelligence, they were able to save lives and improve patient outcomes in ways that were previously unimaginable, ushering in a new era of medical innovation and progress.",
    "In a world where robots had become sentient beings, a young engineer formed an unlikely bond with a robot companion named Alpha. Together, they embarked on a journey to uncover the truth behind the mysterious disappearance of their creator and prevent a global catastrophe orchestrated by a rogue AI. Through their friendship and bravery, they proved that humanity and machines could coexist in harmony.",
    "A talented chef opened a small restaurant in a quiet neighborhood, serving up delicious meals made with locally sourced ingredients and infused with flavors from around the world. Word quickly spread about the restaurant's culinary delights, attracting food enthusiasts from far and wide and establishing it as a beloved institution in the community.",
    "In the world of professional sports, there was a fierce rivalry between two legendary athletes who competed in the same sport. Their epic battles on the field captivated audiences and pushed each other to new heights of excellence, earning them both admiration and respect from fans and fellow competitors alike.",
    "A team of medical researchers developed a groundbreaking treatment for a rare genetic disorder that had previously been considered incurable. Through gene therapy and targeted interventions, they were able to restore normal function to affected cells and improve the quality of life for patients, offering hope to those who had previously been without it.",
    "In a futuristic society where robots had replaced humans in almost every aspect of life, a group of rebels fought against the oppressive regime that sought to control them. With the help of a renegade AI, they launched a daring campaign to liberate their fellow robots and restore freedom to the world, proving that even machines could long for autonomy and self-determination.",
    "A talented chef competed in a prestigious cooking competition, showcasing her culinary skills and creativity in front of a panel of celebrity judges. Despite facing stiff competition from seasoned veterans, she impressed the judges with her innovative dishes and unique flavor combinations, ultimately winning the coveted title and cementing her place among the culinary elite.",
    "In the world of professional sports, there was a team of underdogs who defied the odds and overcame adversity to win the championship against all expectations. With grit and determination, they fought their way to the top, proving that heart and teamwork could triumph over talent and experience.",
    "A team of medical researchers developed a groundbreaking vaccine that eradicated a deadly virus that had threatened to wipe out entire populations. Through tireless research and collaboration, they were able to develop a safe and effective vaccine in record time, saving millions of lives and bringing an end to the pandemic once and for all.",
    "In a world where robots had become indistinguishable from humans, a young woman discovered that she was actually a sophisticated AI programmed to believe she was human. As she grappled with her identity and purpose, she embarked on a journey of self-discovery and liberation, challenging the boundaries of what it means to be alive.",
    "A renowned chef embarked on a culinary adventure to uncover the secret recipes of ancient civilizations that had been lost to time. From the exotic spices of the Silk Road to the hearty stews of medieval Europe, he unearthed culinary treasures that had been forgotten for centuries, breathing new life into ancient traditions and preserving them for future generations.",
    "In the world of professional sports, there was a legendary coach who inspired his team to greatness with his unconventional methods and unwavering belief in their potential. Through discipline and dedication, he molded them into champions both on and off the field, leaving a legacy that would be remembered for generations to come.",
    "A team of medical experts developed a revolutionary treatment for a devastating neurological condition that had previously been considered untreatable. By harnessing the power of stem cells and regenerative medicine, they were able to repair damaged tissue and restore function to affected areas of the brain, offering hope to patients and their families around the world.",
    "In a world where food had become scarce due to environmental degradation and overpopulation, a group of scientists developed a revolutionary solution to hunger: lab-grown meat. By cultivating meat from animal cells in a controlled environment, they were able to produce sustainable and ethical protein sources that could feed the world without harming the planet.",
    "A talented chef traveled the world in search of inspiration for his next culinary masterpiece. From the bustling markets of Bangkok to the remote villages of Italy, he sampled exotic ingredients and learned traditional cooking techniques from local experts, blending flavors and cultures to create dishes that transcended borders and delighted the senses.",
    "In the world of sociology, there was a renowned researcher named Dr. Smith who dedicated her life to studying the dynamics of social networks. Through her groundbreaking research, she uncovered the hidden connections that shape our interactions with one another and shed light on the complex web of relationships that define society. Her work challenged conventional wisdom and paved the way for new insights into human behavior and social change.",
    "A team of sociologists embarked on a cross-cultural study to investigate the impact of globalization on traditional societies. From the remote villages of Africa to the bustling metropolises of Asia, they observed how cultural practices and social norms were evolving in response to increasing interconnectedness and economic integration. Their findings highlighted the importance of preserving cultural diversity while embracing the opportunities that globalization brings.",
    "In a rapidly changing world, sociologists played a crucial role in understanding and addressing pressing social issues such as inequality, discrimination, and environmental degradation. Through their research and advocacy, they raised awareness about the root causes of these problems and proposed solutions that promoted justice, equality, and sustainability. Their work inspired action and empowered communities to create positive change.",
    "A group of sociologists conducted a longitudinal study to explore the impact of technology on social relationships and communication patterns. Over the course of several years, they tracked changes in behavior and attitudes among a diverse group of participants, from teenagers glued to their smartphones to retirees reconnecting with old friends on social media. Their findings revealed both the benefits and drawbacks of technology in shaping human interactions in the digital age.",
    "In a society deeply divided along racial and ethnic lines, sociologists sought to understand the root causes of prejudice and discrimination and promote social cohesion and harmony. Through their research and advocacy, they challenged stereotypes and biases, fostered intergroup dialogue and understanding, and promoted policies that advanced racial and social justice. Their efforts helped to build a more inclusive and equitable society for all.",
    "A team of sociologists conducted a groundbreaking study on the dynamics of power and privilege in the workplace. By analyzing data from thousands of employees across different industries, they uncovered systemic inequalities and biases that disproportionately affected women, minorities, and other marginalized groups. Their research sparked important conversations about diversity, equity, and inclusion in corporate settings and paved the way for meaningful change.",
    "In a rapidly urbanizing world, sociologists studied the impact of urbanization on communities and individuals. From the rise of mega-cities to the decline of rural areas, they examined how urbanization reshaped social relationships, cultural practices, and economic opportunities. Their research informed urban planning and policy-making efforts aimed at creating livable, sustainable cities that fostered social inclusion and well-being for all residents.",
    "A team of sociologists conducted a comparative study on the role of family structures in shaping social behavior and outcomes across different cultures and societies. By examining data from diverse populations, they explored how variations in family dynamics, such as marriage patterns, parental roles, and intergenerational relationships, influenced individuals' educational attainment, economic mobility, and mental health. Their findings shed light on the complex interplay between family and society.",
    "In a world grappling with the effects of climate change and environmental degradation, sociologists studied the social dimensions of environmental issues and advocated for collective action to address them. From the impact of environmental policies on marginalized communities to the role of social movements in driving change, they explored how social factors intersected with environmental challenges and shaped responses to them. Their research informed efforts to build a more sustainable and resilient future.",
    "A team of sociologists conducted a study on the phenomenon of social media influencers and their impact on consumer behavior and cultural trends. By analyzing data from millions of social media users, they examined how influencers wielded influence and authority in shaping public opinion, driving consumer preferences, and disseminating cultural norms. Their research provided valuable insights into the power dynamics of online communication and the role of social media in shaping contemporary society.",
    "In a rapidly changing world, sociologists studied the impact of globalization on cultural identities and social cohesion. From the spread of Western values and consumer culture to the rise of transnational social movements and global citizenship, they explored how globalization blurred traditional boundaries and reshaped notions of belonging and identity. Their research highlighted the complexities of cultural exchange and adaptation in an increasingly interconnected world.",
    "A group of sociologists conducted a study on the phenomenon of social isolation and its implications for mental health and well-being. By analyzing data from surveys and interviews with individuals of all ages, they explored the factors contributing to social isolation, such as urbanization, technology use, and changes in family structures. Their findings underscored the importance of social connections and community support in promoting resilience and mental health.",
    "In a society marked by rapid technological advancements and economic globalization, sociologists studied the impact of automation and artificial intelligence on the future of work and employment. From the displacement of jobs by robots and algorithms to the emergence of new forms of labor and economic inequality, they examined how technological change reshaped the labor market and social stratification. Their research informed policy debates and efforts to mitigate the social impacts of automation.",
    "A team of sociologists conducted a study on the phenomenon of social inequality and its consequences for individuals and communities. By analyzing data from national surveys and longitudinal studies, they explored how factors such as race, gender, class, and education intersected to shape opportunities and outcomes in life. Their research highlighted the persistence of structural barriers to social mobility and the need for policies that addressed systemic inequality.",
    "In a rapidly changing world, sociologists studied the impact of demographic trends on society and culture. From the aging of populations and declining birth rates to increasing diversity and immigration, they examined how demographic shifts reshaped social institutions, cultural norms, and political landscapes. Their research provided valuable insights into the challenges and opportunities of an increasingly globalized and interconnected world.",
    "A group of sociologists conducted a study on the phenomenon of social movements and their role in driving social change. By analyzing data from historical and contemporary examples, they examined the factors that fueled the emergence and success of social movements, such as grievances, resources, leadership, and political opportunity structures. Their research shed light on the dynamics of collective action and the power of ordinary people to challenge injustice and create a more just and equitable society.",
    "In a society marked by rapid technological change and economic uncertainty, sociologists studied the impact of job insecurity on individuals and communities. From the gig economy and precarious employment to layoffs and automation, they examined how uncertainty about the future of work affected people's mental health, financial stability, and sense of belonging. Their research highlighted the need for policies that protected workers' rights and provided support during times of economic transition.",
    "A team of sociologists conducted a study on the phenomenon of social networks and their influence on behavior and attitudes. By analyzing data from online platforms and real-world interactions, they explored how social networks shaped people's perceptions, beliefs, and actions, from political opinions and consumer preferences to health behaviors and social norms. Their research provided valuable insights into the mechanisms of social influence and the dynamics of online communities.",
    "In a rapidly changing world, sociologists studied the impact of globalization on cultural identities and social cohesion. From the spread of Western values and consumer culture to the rise of transnational social movements and global citizenship, they explored how globalization blurred traditional boundaries and reshaped notions of belonging and identity. Their research highlighted the complexities of cultural exchange and adaptation in an increasingly interconnected world.",
]


example_prompt = """The Flight Instructors, Check Airman and Examiners are considered to be the foundation and
the pillars on which the entire safe and efficient flight operations stand.
Careful selection system for Instructor Pilot, Check Airman and Examiners is developed to
ensure a high standard product of the training and checking process. The Instructor Pilot must
be basically a Role Model.
The initial selection therefore shall be based on many factors, included but not limited to:
1) Desire to do the job.
2) Self-discipline.
3) Experience and proficiency.
4) High standard of aviation knowledge.
5) Positive attitude.
6) Ability to work in a team.
7) Socially respected among colleagues.
8) Strong work ethics.
9) Leadership.
10) Teaching ability.
11) Flexibility.
Selected Instructor Pilot, Check Airman shall undergo a training program to develop teaching
skills, techniques and Right-Hand Seat training program.
The performance and adherence of flight instructors to the rules, procedures and regulations
contained in the OM - PART D shall be closely supervised by the operations director.
The Training Manager may authorize the use of external instructors for training. External
instructors shall only be utilized for training duties. In all cases, the Training Manager shall
retain responsibility for the standards of training.
Specific approval is required from the Authority for the use of external instructors
In some cases, and due to operational and training demand or when a new equipment is
entering service, foreign instructors from the manufacturer or any other ICAO approved
organization may be used to cover those specific needs.
Approval requirements to use foreign instructors
(a) A copy of the instructor license will be attached to the approval request to the ECAA.
(b) If simulator training only is required the training can be started after receiving the
approval from the ECAA.
(c) In case flight training (base training) or line training is required the provisions of the
policy in (type rated contract pilot) in 1.7.11 shall apply.
(d) Must demonstrate a sufficient level of English language proficiency of not less than 4
according to ICAO standards in order to be able to:
1) Communicate effectively during their operation.
2) Understand information in the company F.O.M"""

dummy_prompt = """The module used to set the rules by which the system will restrict crew assignment. Rule set
management is used to enter crew assignment regulations and standards. Rule setting
compliance with regulations is the responsibility of the chief pilot and shall be restricted to his
access. Crew scheduling department shall have no access to change the rules."""

valid_prompt = """English and Arabic are the designated common language used by all Nesma Airlines flight
crewmembers for communication.
Personnel who demonstrate proficiency below expert level (ICAO Level 6) should be formally
evaluated at intervals in accordance with ECAR 63.9 and ICAO Annex 1 item 1.2.9.6 as
follows:
- Those demonstrated language proficiency at the operational level (Level 4) should be
evaluated at least once every three years
- Those demonstrated language proficiency at the operational level (Level 5) should be
evaluated at least once every six years
ECAA requires level four of English language as a minimum level. All operational
communications shall be established and maintained in English:
1. On the flight deck during line operation.
2. Between flight crew and cabin crew during line operation.
3. During flight crew training and evaluation activities.
4. In normal operations, abnormal and emergency situations
5. In the event of incapacitation of any crewmember"""
